E_learn/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views

from students.views import *
from lessons.views import *
urlpatterns = [
    path("admin/", admin.site.urls),
    path("", home, name='home'),
    path("about/", about, name='about'),
    path("register/", RegisterView.as_view(), name='register'),
    path("login/", CustomLoginView.as_view(), name='login'),
    path("logout/", auth_views.LogoutView.as_view(template_name='students/logout.html'), name='logout'),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('profile/', profile, name='profile'),
    path('courses/', courses, name='courses'),
    path('teachers/', teachers, name='teachers'),
    path('teacher_profile/<int:id>/', teacher_profile, name='teacher_profile'),
    path('profile/<int:pk>', owner_profile, name='owner_profile'),
    path('password-reset/', ResetPasswordView.as_view(), name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='students/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='students/password_reset_complete.html'),
         name='password_reset_complete'),
    path('profile/update/', update_profile, name='update_profile'),
    path('password-change/', ChangePasswordView.as_view(), name='password_change'),
    
    path(r'^ckeditor/', include('ckeditor_uploader.urls')), #ckeditor
    
    
    path('lesson/', include('lessons.urls', namespace='lesson')),
    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lessons/urls.py
from django.contrib import admin
from django.urls import path
from lessons import views
app_name = 'lessons'
urlpatterns = [
    path('search/', views.home, name='search'),
    path('course/liked_modules/', views.liked_modules, name='liked_modules'),
    path('course/view_comments/', views.view_comments, name='view_comments'),
    path('course/saved_playlists/', views.saved_playlists, name='saved_playlists'),
    
    path('<slug:category_slug>', views.home, name='index'),
    path('course/<slug:course_slug>/', views.course_detail, name='course_detail'),
    path('course/<slug:course_slug>/save', views.AddSave.as_view(), name='save_playlist'),
    

    path('course/<slug:course_slug>/<slug:module_slug>/', views.ModuleDetailView.as_view(), name='module_detail'),
    path('course/<slug:course_slug>/<slug:module_slug>/like', views.AddLike.as_view(), name='like'),
    path('course/<slug:course_slug>/<slug:module_slug>/dislike', views.AddDislike.as_view(), name='dislike'),
    path('course/<slug:course_slug>/<slug:module_slug>/edit/<int:comment_id>/', views.edit_comment, name='edit_comment'),
    path('course/<slug:course_slug>/<slug:module_slug>/update/<int:comment_id>/', views.update_comment, name='update_comment'),
    path('course/<slug:course_slug>/<slug:module_slug>/delete/<int:comment_id>/', views.delete_comment, name='delete_comment'),
    

]

students/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
# Create your models here.

class Profile(models.Model):
    
    STUDENT = 'student'
    TEACHER = 'teacher'

    STATUS_CHOICES = [
        (STUDENT, 'Student'),
        (TEACHER, 'Teacher'),
    ]
    
    
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='profile_pic', default="default.jpg")
    bio= models.TextField()
    status = models.CharField(max_length=7, choices=STATUS_CHOICES, default=STUDENT)
    
    
    class Meta:
        verbose_name = "Профиль"
        verbose_name_plural = "Профили"
        
    
    
    def __str__(self) -> str:
        return self.user.username
        
    # def save(self, *args, **kwargs):
    #     super().save()

    #     img = Image.open(self.image.path)

    #     if img.height > 100 or img.width > 100:
    #         new_img = (100, 100)
    #         img.thumbnail(new_img)
    #         img.save(self.image.path)

students/forms.py
from django import forms 
from django.contrib.auth.models import User 
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from students.models import Profile

class RegisterForm(UserCreationForm):
    STUDENT = 'student'
    TEACHER = 'teacher'

    STATUS_CHOICES = [
        (STUDENT, 'Student'),
        (TEACHER, 'Teacher'),
    ]
    
    first_name = forms.CharField(max_length=100, required=True, widget=forms.TextInput(attrs={'placeholder': 'Enter your name',
                                                                                              'class': 'box'
                                                                                              }))
    
    last_name = forms.CharField(max_length=100, required=True, widget=forms.TextInput(attrs={'placeholder': 'Last Name',
                                                                                              'class': 'box'
                                                                                              }))
    
    username = forms.CharField(max_length=100, required=True, widget=forms.TextInput(attrs={'placeholder': 'Username',
                                                                                              'class': 'box'
                                                                                              }))
    
    email = forms.EmailField(required=True, widget=forms.TextInput(attrs={'placeholder': 'Email',
                                                                          'class': 'box'
                                                                          }))
    
    password1 = forms.CharField(max_length=50,required=True, widget=forms.PasswordInput(attrs={'placeholder': 'Password',
                                                                                              'class': 'box',
                                                                                              'data-toggle': 'password',
                                                                                              'id': 'password'
                                                                                              }))
    
    password2 = forms.CharField(max_length=50,required=True, widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password',
                                                                                              'class': 'box',
                                                                                              'data-toggle': 'password',
                                                                                              'id': 'password'
                                                                                              }))
    
    status = forms.ChoiceField(
        choices=STATUS_CHOICES,
        required=True,
        widget=forms.Select(attrs={
            'class': 'box'
        })
    )
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2', 'status']
        
    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        if commit:
            user.save()
            # Check if the profile already exists
            profile, created = Profile.objects.get_or_create(user=user)
            profile.status = self.cleaned_data['status']
            profile.save()
        return user
    
    
class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput(attrs={'placeholder': 'Username',
                                                             'class': 'box'}))
    
    password = forms.CharField(max_length=50,
                               required=True,
                               widget=forms.PasswordInput(attrs={'placeholder': 'Password',
                                                                 'class': 'box',
                                                                 'data-toggle': 'password',
                                                                 'id': 'password',
                                                                 'name': 'password',
                                                                 }))
    remember_me = forms.BooleanField(required=False)
    
    class Meta:
        model = User
        fields = ['username', 'password', 'remember_me']
        
        
class UpdateUserForm(forms.ModelForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput(attrs={'class': 'box'}))
    email = forms.EmailField(required=True,
                             widget=forms.TextInput(attrs={'class': 'box'}))
    
    first_name = forms.CharField(required=True,
                             widget=forms.TextInput(attrs={'class': 'box'}))
    
    last_name = forms.CharField(required=True,
                             widget=forms.TextInput(attrs={'class': 'box'}))

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']


class UpdateProfileForm(forms.ModelForm):
    image = forms.ImageField(widget=forms.FileInput(attrs={'class': 'box'}))
    bio = forms.CharField(widget=forms.Textarea(attrs={'class': 'box', 'rows': 5}))

    class Meta:
        model = Profile
        fields = ['image', 'bio']

students/views.py
from django.shortcuts import render, redirect 
from django.contrib import messages
from django.views import View
from django.contrib.auth.views import LoginView, PasswordChangeView, PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from students.models import Profile
from lessons.models import Comment, Lesson
from .forms import LoginForm, RegisterForm, UpdateProfileForm, UpdateUserForm

# Create your views here.

@login_required
def profile(request):
    user_comments_count = Comment.objects.filter(author=request.user).count()
    context = {
        'count': user_comments_count
    }
    return render(request, 'students/profile.html', context)


@login_required
def update_profile(request):
    if request.method == 'POST':
        user_form = UpdateUserForm(request.POST, instance=request.user)
        profile_form = UpdateProfileForm(request.POST, request.FILES, instance=request.user.profile)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Your profile is updated successfully')
            return redirect(to='profile')
    else:
        user_form = UpdateUserForm(instance=request.user)
        profile_form = UpdateProfileForm(instance=request.user.profile)
    return render(request, 'students/update.html', {'user_form': user_form, 'profile_form': profile_form})

from django.contrib.auth.models import User

def owner_profile(request, pk):
    if request.method == 'GET':
        owner = User.objects.get(pk=pk)
        user_comments_count = Comment.objects.filter(author=owner).count()
        context = {
        'owner': owner,
        'count': user_comments_count
        }
        return render(request, 'students/owner_profile.html', context)        








class RegisterView(View):
    form_class = RegisterForm
    initial = {'key': 'value'}
    template_name = 'students/register.html'

    def get(self, request, *args, **kwargs):
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)

        if form.is_valid():
            form.save()

            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for {username}')

            return redirect(to='/login')

        return render(request, self.template_name, {'form': form})
    
    def dispatch(self, request, *args, **kwargs):
        # will redirect to the home page if a user tries to access the register page while logged in
        if request.user.is_authenticated:
            return redirect(to='/')

        # else process dispatch as it otherwise normally would
        return super(RegisterView, self).dispatch(request, *args, **kwargs)
    
class CustomLoginView(LoginView):
    form_class = LoginForm
    authentication_form = LoginForm
    redirect_authenticated_user = True
    template_name = 'students/login.html'
    def form_valid(self, form):
        remember_me = form.cleaned_data.get('remember_me')

        if not remember_me:
            # set session expiry to 0 seconds. So it will automatically close the session after the browser is closed.
            self.request.session.set_expiry(0)

            # Set session as modified to force data updates/cookie to be saved.
            self.request.session.modified = True

        # else browser session will be as long as the session cookie time "SESSION_COOKIE_AGE" defined in settings.py
        return super(CustomLoginView, self).form_valid(form)
    
class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'students/password_reset.html'
    email_template_name = 'students/password_reset_email.html'
    subject_template_name = 'students/password_reset_subject.txt'
    success_message = "We've emailed you instructions for setting your password, " \
                      "if an account exists with the email you entered. You should receive them shortly." \
                      " If you don't receive an email, " \
                      "please make sure you've entered the address you registered with, and check your spam folder."
    success_url = reverse_lazy('home')
    
class ChangePasswordView(SuccessMessageMixin, PasswordChangeView):
    template_name = 'students/change_password.html'
    success_message = "Successfully Changed Your Password"
    success_url = reverse_lazy('home')
    
    
def teachers_profile1(request):
    teachers = Profile.objects.filter(status='teacher')
    lessons = Lesson.objects.all()
    #найти уроки по пользователю который в teachers и передать через словарь
    
    teacher_lesson_counts = {
        teacher.user.id: Lesson.objects.filter(owner=teacher.user).count()
        for teacher in teachers
    }
    teacher_module_counts = {}

    for teacher in teachers:
        # Find lessons taught by the current teacher
        lessons_taught = Lesson.objects.filter(owner=teacher.user)
        
        # Calculate the total module count for the current teacher
        total_module_count = sum(lesson.modules.count() for lesson in lessons_taught)
        
        # Store the total module count in the dictionary
        teacher_module_counts[teacher.user.id] = total_module_count
        
        
        #TODO to finish
        total_likes_count = sum(module.likes.count() for lesson in lessons_taught for module in lesson.modules.all())
    
    
    context = {
        "teachers": teachers,
        "lessons": lessons,
        "teacher_lesson_counts": teacher_lesson_counts,
        "teacher_module_counts": teacher_module_counts
    }
    return render(request, "teachers.html", context)


def teachers(request):
    teachers = Profile.objects.filter(status='teacher')
    
    # Initialize an empty dictionary to store various counts for each teacher
    teacher_counts = {}

    for teacher in teachers:
        # Find lessons taught by the current teacher
        lessons_taught = Lesson.objects.filter(owner=teacher.user)
        
        # Calculate the total counts for the current teacher
        total_lesson_count = lessons_taught.count()
        total_module_count = sum(lesson.modules.count() for lesson in lessons_taught)
        total_likes_count = sum(module.likes.count() for lesson in lessons_taught for module in lesson.modules.all())
        
        # Store the counts in the dictionary
        teacher_counts[teacher.user.id] = {
            'total_lesson_count': total_lesson_count,
            'total_module_count': total_module_count,
            'total_likes_count': total_likes_count
        }
    
    context = {
        "teachers": teachers,
        "teacher_counts": teacher_counts
    }
    return render(request, "teachers.html", context)

def teacher_profile(request, id):
    user = User.objects.get(pk=id)
    teacher = Profile.objects.get(user=user)
    lessons = Lesson.objects.filter(owner=user)
    total_lesson_count = lessons.count()
    total_module_count = sum(lesson.modules.count() for lesson in lessons)
    total_likes_count = sum(module.likes.count() for lesson in lessons for module in lesson.modules.all())
    total_comment_count = sum(Comment.objects.filter(module=module).count() for lesson in lessons for module in lesson.modules.all())
    context = {
        'teacher': teacher,
        'lessons': lessons,
        'total_lesson_count': total_lesson_count,
        'total_module_count': total_module_count,
        'total_likes_count': total_likes_count,
        'total_comment_count': total_comment_count
    }
    return render(request, 'students/teacher_profile.html', context)

def courses(request):
    lessons = Lesson.objects.all()
    context = {
        'lessons': lessons
    }
    return render(request, 'courses.html', context)

students/templates/students/change_password.html
{% extends "base.html" %}
{% load static %}

{% block title %} <title>Change Password</title> {% endblock %}

{% block content %}
<section class="form-container">
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% if form.errors %}
        <div class="alert alert-danger alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
            <div id="form_errors">
                {% for key, value in form.errors.items %}
                <strong>{{ value }}</strong>
                {% endfor %}
            </div>
        </div>
        {% endif %}

        <p>Old Password</p>
                                                <input type="password" name="old_password" autocomplete="new-password"
                                                       class="box" required id="id_old_password"
                                                       placeholder="Enter Old Password"/>

        <p>New Password</p>
        <input type="password" name="new_password1" autocomplete="new-password"
                                                       class="box" required id="id_new_password1"
                                                       placeholder="Enter new password"/>

        <p>New Password Confirmation</p>
        <input type="password" name="new_password2" autocomplete="new-password"
                                                       required id="id_new_password2" class="box"
                                                       placeholder="Confirm new password"/>
        

        <input type="submit" value="Change Password" name="submit" class="btn btn-primary btn-block">
    </form>
</section>
{% endblock %}

students/templates/students/login.html
{% extends "base.html" %}
{% load static %}

{%block title %} <title>Login</title> {% endblock %} 
{% block content %}

<section class="form-container">
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% if form.errors %}
        <div class="alert alert-danger alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
            <div id="form_errors">
                {% for key, value in form.errors.items %}
                <strong>{{ value }}</strong>
                {% endfor %}
            </div>
        </div>
        {% endif %}
        <h3>login now</h3>
        <a href="{% url 'social:begin' 'github' %}" class="btn btn-link btn-lg active btn-block">Sign in with GitHub</a>
        <a href="{% url 'social:begin' 'google-oauth2' %}" class="btn btn-link btn-lg active btn-block">Sign in with Google</a>
        <hr>
        <p style="text-align: center; margin-top: 20px;"><strong>OR</strong></p>
        <hr>
        <p>Username <span>*</span></p>
        {% csrf_token %}
        {{form.username}}
        <p>Password <span>*</span></p>
        {{form.password}}
        <div class="form-row">
            <div class="col-md-10 offset-md-1">
                <div class="form-group">
                    {{ form.remember_me }}
                    <label class="ara3hunna"> Remember me </label>
                </div>
            </div>
        </div>

        <div class=" remember-field ">  
            <a href="{% url 'register' %}" class="ara4matic">Don't have an account yet? Go to signup</a>
            <a href="{% url 'password_reset' %}" class=""><i>Forgot Password?</i></a>
        </div>

        <input type="submit" value="Sign In" name="submit" class="btn btn-primary btn-block">
    </form>
</section>

{% endblock %}











{% block footer %}

<footer class="footer">

   &copy; copyright @ 2022 by <span>mr. web designer</span> | all rights reserved!

</footer>
{% endblock %}

students/templates/students/logout.html
{% extends "base.html" %}
{% load static %}
{% block title %}<title>Logout</title>{% endblock title %}
{% block content %}
<div class="form-container">
    <div class="row justify-content-center">
        <div class="alert alert-danger alert-dismissible" role="alert">
        <div class="card-body">
          <h5 class="card-title font-weight-bold"  style="font-size: 24px;">You have been logged out</h5>
          <p class="card-text" style="font-size: 19px;">
            Thanks for your time, contact me for any comments or suggestions using my email address.
          </p>
          <hr>
        </div>
      </div>
      <a href="{% url 'login' %}" class="btn btn-primary mx-auto">Sign in again</a>
    </div>
  </div>
  


{% endblock content %}

students/templates/students/owner_profile.html
{% extends "base.html" %}
{% load static %}

{% block title %} <title>Profile</title> {% endblock %}


{% block content %}
<section class="user-profile">

   <h1 class="heading">your profile</h1>

   <div class="info">

      <div class="user">
         <img src="{{ owner.profile.image.url }}" alt="">
         <h3>{{user.first_name}} {{user.last_name}}</h3>
         <p>{{owner.username}}</p>
         <!-- <a href="{% url 'update_profile' %}" class="inline-btn">update profile</a> -->
      </div>
      <div class="box-container">
   
         <div class="box">
            <div class="flex">
               <i class="fas fa-bookmark"></i>
               <div>
                  <span>{{owner.save_playlist.count}}</span>
                  <p>saved playlist</p>
               </div>
            </div>
            <a href="#" class="inline-btn">view playlists</a>
         </div>
   
         <div class="box">
            <div class="flex">
               <i class="fas fa-heart"></i>
               <div>
                  <span>{{owner.likes.count}}</span>
                  <p>videos liked</p>
               </div>
            </div>
            <a href="#" class="inline-btn">view liked</a>
         </div>
   
         <div class="box">
            <div class="flex">
               <i class="fas fa-comment"></i>
               <div>
                  <span>{{count}}</span>
                  <p>videos comments</p>
               </div>
            </div>
            <a href="#" class="inline-btn">view comments</a>
         </div>
   
      </div>
   </div>

</section>

{% endblock %}

students/templates/students/password_reset.html
{% extends "base.html" %}
{% load static %}
{% block title %} <title>Password Reset</title> {% endblock %}

{% block content %}
<section class="form-container">
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% if form.errors %}
        <div class="alert alert-danger alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
            <div id="form_errors">
                {% for key, value in form.errors.items %}
                <strong>{{ value }}</strong>
                {% endfor %}
            </div>
        </div>
        {% endif %}
        <h3>Forgot Password?</h3>
        <input type="email" name="email"  class="box"
                                               autocomplete="email" maxlength="254" required id="id_email"
                                               placeholder="Enter email">
        
        

        <div class=" remember-field ">  
            <a href="{% url 'register' %}" class="ara4matic">Create A New Account</a><br><br>
            <a href="{% url 'login' %}" class="ara4matic">Back To Login</a><br>
        </div>

        <input type="submit" value="Submit" name="submit" class="btn btn-primary btn-block">
    </form>
</section>

{% endblock %}

students/templates/students/password_reset_complete.html
{% extends "base.html" %}
{% load static %}
{% block content %}

    <section class="form-container">
    <div class="container my-3 p-3">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <div class="alert alert-benz alert-dismissible" role="alert">
                    <div class="alert-message">
                        Your password has been set. You may go ahead and <a href="{% url 'login' %}">Login Here</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

students/templates/students/password_reset_confirm.html
{% extends "base.html" %}
{% load static %}
{% block title %} <title>Password Reset</title> {% endblock %}

{% block content %}
<section class="form-container">
    {% if validlink %}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% if form.errors %}
        <div class="alert alert-danger alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
            <div id="form_errors">
                {% for key, value in form.errors.items %}
                <strong>{{ value }}</strong>
                {% endfor %}
            </div>
        </div>
        {% endif %}
        <label class="small mb-1" for="id_new_password1">New Password</label>
        <input type="password" name="new_password1" autocomplete="new-password"
                                                       class="box" required id="id_new_password1"
                                                       placeholder="Enter password"/>

        <label class="small mb-1" for="id_new_password2">New Password Confirmation</label>
        <input type="password" name="new_password2" autocomplete="new-password"
                                                       required id="id_new_password2" class="box"
                                                       placeholder="Confirm password"/>
        

        <div class=" remember-field ">  
            <a href="{% url 'register' %}" class="ara4matic">Create A New Account</a><br><br>
            <a href="{% url 'login' %}" class="ara4matic">Back To Login</a><br>
        </div>

        <input type="submit" value="Reset Password" name="submit" class="btn btn-primary btn-block">
    </form>
</section>
{% else %}
<div class="alert alert-warning">
    The password reset link was invalid, possibly because it has already been used.
    Please request a new password reset.
</div>
{% endif %}


{% endblock %}

students/templates/students/profile.html
{% extends "base.html" %}
{% load static %}

{% block title %} <title>Profile</title> {% endblock %}


{% block content %}
<section class="user-profile">

   <h1 class="heading">your profile</h1>

   <div class="info">

      <div class="user">
         <img src="{{ user.profile.image.url }}" alt="">
         <h3>{{user.first_name}} {{user.last_name}}</h3>
         <p>student</p>
         <a href="{% url 'update_profile' %}" class="inline-btn">update profile</a>
      </div>
      <div class="box-container">
   
         <div class="box">
            <div class="flex">
               <i class="fas fa-bookmark"></i>
               <div>
                  <span>{{user.save_playlist.count}}</span>
                  <p>saved playlist</p>
               </div>
            </div>
            <a href="{% url "lesson:saved_playlists"  %}" class="inline-btn">view playlists</a>
         </div>
   
         <div class="box">
            <div class="flex">
               <i class="fas fa-heart"></i>
               <div>
                  <span>{{user.likes.count}}</span>
                  <p>videos liked</p>
               </div>
            </div>
            <a href="{% url "lesson:liked_modules"  %}" class="inline-btn">view liked</a>
         </div>
   
         <div class="box">
            <div class="flex">
               <i class="fas fa-comment"></i>
               <div>
                  <span>{{count}}</span>
                  <p>videos comments</p>
               </div>
            </div>
            <a href="{% url "lesson:view_comments"  %}" class="inline-btn">view comments</a>
         </div>
   
      </div>
   </div>

</section>

{% endblock %}

students/templates/students/teacher_profile.html
{% extends "base.html" %}
{% load static %}

{% block title %} <title>Teachers</title> {% endblock %}

{% load custom_filters %}
{% block content %}

   <title>Teacher Profile</title>




<section class="teacher-profile">

   <h1 class="heading">profile details</h1>

   <div class="details">
      <div class="tutor">
         <img src="{{teacher.image.url}}" alt="">
         <h3>{{teacher.user.first_name}} {{teacher.user.last_name}}</h3>
         <span>{{teacher.user.username}}</span>
      </div>
      <div class="flex">
         <p>total playlists : <span>{{total_lesson_count}}</span></p>
         <p>total videos : <span>{{total_module_count}}</span></p>
         <p>total likes : <span>{{total_likes_count }}</span></p>
         <p>total comments : <span>{{total_comment_count}}</span></p>
      </div>
   </div>

</section>

<section class="courses">

   <h1 class="heading">our courses</h1>

   {% for lesson in lessons %}
   <div class="box-container">

      <div class="box">
         <div class="thumb">
            <img src="{{lesson.image.url}}" alt="">
            <span>{{lesson.modules.count}}</span>
         </div>
         <h3 class="title">{{lesson.title}}</h3>
         <a href="{% url "lesson:course_detail" lesson.slug %}" class="inline-btn">view playlist</a>
      </div>
   {% endfor %}
      
   </div>

</section>










{% endblock %}


{% block footer %}
<footer class="footer">

   &copy; copyright @ 2022 by <span>mr. web designer</span> | all rights reserved!

</footer>

{% endblock %}