E_learn/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views

from students.views import *
from lessons.views import *
urlpatterns = [
    path("admin/", admin.site.urls),
    path("", home, name='home'),
    path("about/", about, name='about'),
    path("register/", RegisterView.as_view(), name='register'),
    path("login/", CustomLoginView.as_view(), name='login'),
    path("logout/", auth_views.LogoutView.as_view(template_name='students/logout.html'), name='logout'),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('profile/', profile, name='profile'),
    path('courses/', courses, name='courses'),
    path('teachers/', teachers, name='teachers'),
    path('teacher_profile/<int:id>/', teacher_profile, name='teacher_profile'),
    path('profile/<int:pk>', owner_profile, name='owner_profile'),
    path('password-reset/', ResetPasswordView.as_view(), name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='students/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='students/password_reset_complete.html'),
         name='password_reset_complete'),
    path('profile/update/', update_profile, name='update_profile'),
    path('password-change/', ChangePasswordView.as_view(), name='password_change'),
    
    path(r'^ckeditor/', include('ckeditor_uploader.urls')), #ckeditor
    
    
    path('lesson/', include('lessons.urls', namespace='lesson')),
    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lessons/urls.py
from django.contrib import admin
from django.urls import path
from lessons import views
app_name = 'lessons'
urlpatterns = [
    path('search/', views.home, name='search'),
    path('course/liked_modules/', views.liked_modules, name='liked_modules'),
    path('course/view_comments/', views.view_comments, name='view_comments'),
    path('course/saved_playlists/', views.saved_playlists, name='saved_playlists'),
    
    path('<slug:category_slug>', views.home, name='index'),
    path('course/<slug:course_slug>/', views.course_detail, name='course_detail'),
    path('course/<slug:course_slug>/save', views.AddSave.as_view(), name='save_playlist'),
    

    path('course/<slug:course_slug>/<slug:module_slug>/', views.ModuleDetailView.as_view(), name='module_detail'),
    path('course/<slug:course_slug>/<slug:module_slug>/like', views.AddLike.as_view(), name='like'),
    path('course/<slug:course_slug>/<slug:module_slug>/dislike', views.AddDislike.as_view(), name='dislike'),
    path('course/<slug:course_slug>/<slug:module_slug>/edit/<int:comment_id>/', views.edit_comment, name='edit_comment'),
    path('course/<slug:course_slug>/<slug:module_slug>/update/<int:comment_id>/', views.update_comment, name='update_comment'),
    path('course/<slug:course_slug>/<slug:module_slug>/delete/<int:comment_id>/', views.delete_comment, name='delete_comment'),
    

]

templates/about.html
{% extends "base.html" %}
{% load static %}
{% load lessons_tags %}
{% block title %} <title>About Us</title> {% endblock %} 

{% block content %}
<section class="about">

    <div class="row">
 
       <div class="image">
          <img src="{% static "images/about-img.svg" %}" alt="">
       </div>
 
       <div class="content">
          <h3>why choose us?</h3>
          <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ut dolorum quasi illo? Distinctio expedita commodi, nemo a quam error repellendus sint, fugiat quis numquam eum eveniet sequi aspernatur quaerat tenetur.</p>
          <a href="courses.html" class="inline-btn">our courses</a>
       </div>
 
    </div>
 
    <div class="box-container">
 
       <div class="box">
          <i class="fas fa-graduation-cap"></i>
          <div>
             <h3>+10k</h3>
             <p>online courses</p>
          </div>
       </div>
 
       <div class="box">
          <i class="fas fa-user-graduate"></i>
          <div>
             <h3>+40k</h3>
             <p>brilliant students</p>
          </div>
       </div>
 
       <div class="box">
          <i class="fas fa-chalkboard-user"></i>
          <div>
             <h3>+2k</h3>
             <p>expert tutors</p>
          </div>
       </div>
 
       <div class="box">
          <i class="fas fa-briefcase"></i>
          <div>
             <h3>100%</h3>
             <p>job placement</p>
          </div>
       </div>
 
    </div>
 
 </section> 

{% endblock %}

templates/base.html
{% load static %}
{% load lessons_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   {% block title %} {% endblock %}

   <!-- font awesome cdn link  -->
   
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css">

   <!-- custom css file link  -->
   <link rel="stylesheet" href="{% static "css/style.css" %}">

</head>
<body>

<header class="header">
   
   <section class="flex">

      <a href="{% url 'home' %}" class="logo">Educa.</a>

      <form action="{% if request.GET.q %}{% url "lessons:search" %}{% endif %}" method="get" class="search-form">
         <input type="text" name="q" required placeholder="search courses..." maxlength="100" value="{{request.GET.q}}">
         <button type="submit" class="fas fa-search"></button>
      </form>

      <div class="icons">
         <div id="menu-btn" class="fas fa-bars"></div>
         <div id="search-btn" class="fas fa-search"></div>
         <div id="user-btn" class="fas fa-user"></div>
         <div id="toggle-btn" class="fas fa-sun"></div>
      </div>

      <div class="profile">
         {% if user.is_authenticated %}
         <a href="{% url 'profile' %}"><img src="{{ user.profile.image.url }}" class="image" alt=""></a>
         <h3 class="name">{{user.first_name}} {{user.last_name}}</h3>
         <p class="role">studen</p>
         <a href="{% url 'profile' %}" class="btn">view profile</a>
         {% endif %}
         <div class="flex-btn">
            {% if user.is_authenticated %}
            <a href="{% url 'logout' %}" class="option-btn">logout</a>
            {% else %}
            <a href="{% url 'login' %}" class="option-btn">login</a>
            <a href="{% url 'register' %}" class="option-btn">register</a>
            {% endif %}
         </div>
      </div>

   </section>

</header>   

<div class="side-bar">
   <div id="close-btn">
      <i class="fas fa-times"></i>
   </div>
   {% if user.is_authenticated %}
   <div class="profile">
      <a href="{% url 'profile' %}"><img src="{{ user.profile.image.url }}" class="image" alt=""></a>
      <h3 class="name">{{user.first_name}} {{user.last_name}}</h3>
      <p class="role">{{user.username}}</p>
      <a href="{% url 'profile' %}" class="btn">view profile</a>
   </div>

   {% endif %}

   <nav class="navbar">
      <a href="{% url 'home' %}"><i class="fas fa-home"></i><span>home</span></a>
      <a href="{% url 'about' %}"><i class="fas fa-question"></i><span>about</span></a>
      <a href="{% url 'courses' %}"><i class="fas fa-graduation-cap"></i><span>courses</span></a>
      <a href="{% url 'teachers' %}"><i class="fas fa-chalkboard-user"></i><span>teachers</span></a>
      <a href="contact.html"><i class="fas fa-headset"></i><span>contact us</span></a>
   </nav>

</div>
<!-- Контент на странице -->

{% if messages %}
  <div class="alert alert-success alert-dismissible" role="alert">
    {% for message in messages %}
      <div class="alert-message">{{ message }}</div>
    {% endfor %}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
{% endif %}


{% block content %} {% endblock %}

<!-- Футер -->
{% block footer %} {% endblock %}

 
 <!-- custom js file link  -->
 <script src="{% static "js/script.js" %}"></script>
 
    
 </body>
 </html>

templates/courses.html
{% extends "base.html" %}
{% load static %}

{% block title %} <title>Teachers</title> {% endblock %}

{% load custom_filters %}
{% block content %}
<section class="courses">

    <h1 class="heading">our courses</h1>
 
    <div class="box-container">
 
        {% for lesson in lessons %}
        <div class="box">
            <div class="tutor">
               <a href="{% url "teacher_profile" lesson.owner.pk %}"><img src="{{ lesson.owner.profile.image.url }}" alt="{{lesson.owner}}"></a>
               <div class="info">
                  <a href="{% url "teacher_profile" lesson.owner.pk %}"><h3>{{lesson.owner.first_name}} {{lesson.owner.last_name}}</h3></a>
                  <span>{{lesson.owner}}</span>
                  <br>
                  <span>{{lesson.created|date:"d-m-Y"}}</span>
               </div>
            </div>
            <div class="thumb">
               <a href="{% url "lesson:course_detail" lesson.slug %}"><img src="{{ lesson.image.url }}" alt=""></a>
               <span>{{lesson.modules.count}} videos</span>
            </div>
            <h3 class="title">{{lesson.title}}</h3>
            <a href="{% url "lesson:course_detail" lesson.slug %}" class="inline-btn">view playlist</a>
         </div>
       {% endfor %}
       
 
    </div>
 
 </section>
 


{% endblock %}

templates/home.html
{% extends "base.html" %}
{% load static %}
{% load lessons_tags %}
{% block title %} <title>Home</title> {% endblock %} 

{% block content %}

<section class="home-grid">

   <h1 class="heading">quick options</h1>

   <div class="box-container">

      {% if user.is_authenticated %}
      <div class="box">
         <h3 class="title">likes and comments</h3>
         <p class="likes">total likes : <span>{{user.likes.count}}</span></p>
         <a href="{% url "lesson:liked_modules"  %}" method="GET" class="inline-btn">view likes</a>
         <p class="likes">total comments : <span>{{count}}</span></p>
         <a href="{% url "lesson:view_comments"  %}" class="inline-btn">view comments</a>
         <p class="likes">saved playlists : <span>{{user.save_playlist.count}}</span></p>
         <a href="{% url "lesson:saved_playlists"  %}" class="inline-btn">view playlists</a>
      </div>
      {% endif %}
      

      <div class="box">
         <h3 class="title">top categories</h3>
         <div class="flex">
            {% for category in categories %}
            {% if category.slug == current_category.slug %}
                <a href="{% url "lesson:index" category.slug %}" class="active"><span class="active">{{category.title}}</span></a>

            {% elif current_category.slug == 'all' and category.slug == 'all' %}

               <a href="{% url "lesson:index" category.slug %}" class="active"><span class="active">{{category.title}}</span></a>

            {% else %}
                <a href="{% url "lesson:index" category.slug %}"><span>{{category.title}}</span></a>
            {% endif %}
            {% endfor %}
         </div>
      </div>

      <div class="box">
         <h3 class="title">popular topics</h3>
         <div class="flex">
            <a href="#"><i class="fab fa-html5"></i><span>HTML</span></a>
            <a href="#"><i class="fab fa-css3"></i><span>CSS</span></a>
            <a href="#"><i class="fab fa-js"></i><span>javascript</span></a>
            <a href="#"><i class="fab fa-react"></i><span>react</span></a>
            <a href="#"><i class="fab fa-php"></i><span>PHP</span></a>
            <a href="#"><i class="fab fa-bootstrap"></i><span>bootstrap</span></a>
         </div>
      </div>

      <div class="box">
         <h3 class="title">become a tutor</h3>
         <p class="tutor">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Perspiciatis, nam?</p>
         <a href="{% url 'teachers' %}" class="inline-btn">get started</a>
      </div>

   </div>

</section>



<section class="courses">
   {% if request.GET.q %}
   <h1 class="heading">Search Results {{request.GET.q}}</h1>
   {% else %}
   <h1 class="heading">our courses</h1>
   {% if not lessons %}
   <h1 class="heading">Nothing was found for the query</h1>

   {% endif %}
   {% endif %}
   

   <div class="box-container">
      



   {% for lesson in lessons %}


      <div class="box">
         <div class="tutor">
            <a href="{% url "teacher_profile" lesson.owner.pk %}"><img src="{{ lesson.owner.profile.image.url }}" alt="{{lesson.owner}}"></a>
            <div class="info">
               <a href="{% url "teacher_profile" lesson.owner.pk %}"><h3>{{lesson.owner.first_name}} {{lesson.owner.last_name}}</h3></a>
               <span>{{lesson.owner}}</span>
               <br>
               <span>{{lesson.created|date:"d-m-Y"}}</span>
            </div>
         </div>
         <div class="thumb">
            <a href="{% url "lesson:course_detail" lesson.slug %}"><img src="{{ lesson.image.url }}" alt=""></a>
            <span>{{lesson.modules.count}} videos</span>
         </div>
         <h3 class="title">{{lesson.title}}</h3>
         <a href="{% url "lesson:course_detail" lesson.slug %}" class="inline-btn">view playlist</a>
      </div>

      
      {% endfor %}
         

   </div>





 <!-- asdad -->
   <div class="more-btn">
      <div class="pagination-buttons">
         <!-- <button type="button1" class="page-btn start-page">start</button> -->
         <!-- <button type="button1" class="page-btn active">1</button> -->
                   <button type="button1" class="page-btn prev-page">
                      <p class=" {% if not lessons.has_previous %} disabled {% endif %} ">
                        <a href="{% if lessons.has_previous %}?{% change_params page=lessons.previous_page_number %}{% else %}#{% endif %}">Prev</a>
                      </p>
                   </button>
                      {% for page in lessons.paginator.page_range %}
                      {% if page >= lessons.number|add:-2 and page <= lessons.number|add:2 %}
                      
                         <button class="page-btn {% if lessons.number == page %} active {% endif %}">
                            <a class="button1" href="?{% change_params page=page %}">{{page}}</a>
                         </button>
                      
                      {% endif %}
                      {% endfor %}
                      
       
                      <button type="button1" class="page-btn next-page">
                         <p class="button1 {% if not lessons.has_next %} disabled {% endif %}">
                            <a class="button1" href="{% if lessons.has_next %}?{% change_params page=lessons.next_page_number %}{% else %}#{% endif %}">Next</a>
                         </p>
                      </button>
        
       </div>
   </div>

   
   

</section>





{% endblock %}









{% block footer %}
<footer class="footer">

   &copy; copyright @ 2022 by <span>mr. web designer</span> | all rights reserved!

</footer>

{% endblock %}
   

templates/teachers.html
{% extends "base.html" %}
{% load static %}

{% block title %} <title>Teachers</title> {% endblock %}

{% load custom_filters %}
{% block content %}

<section class="teachers">

   <h1 class="heading">expert teachers</h1>

   <div class="box-container">

      <div class="box offer">
         <h3>become a tutor</h3>
         <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet, itaque ipsam fuga ex et aliquam.</p>
         <a href="{% url 'register' %}" class="inline-btn">get started</a>
      </div>

      {% for teacher in teachers %}
      <div class="box">
         <div class="tutor">
            <a href="{% url "teacher_profile" teacher.user.pk %}"><img src="{{teacher.image.url}}" alt=""></a>
            <div>
               <a href="{% url "teacher_profile" teacher.user.pk %}"><h3>{{teacher.user.first_name}} {{teacher.user.last_name}}</h3></a>
               <span>{{teacher.user.username}}</span>
            </div>
         </div>
         <p>total playlists : <span>{{teacher_counts|get_item:teacher.user.id|get_item:'total_lesson_count'}}</span></p>
         <p>total videos : <span>{{ teacher_counts|get_item:teacher.user.id|get_item:'total_module_count' }}</span></p>
         <p>total likes : <span>{{ teacher_counts|get_item:teacher.user.id|get_item:'total_likes_count' }}</span></p>
         <a href="{% url "teacher_profile" teacher.user.pk %}" class="inline-btn">view profile</a>
      </div>

      {% endfor %}

      

   </div>

</section>


{% endblock %}










{% block footer %}
<footer class="footer">

   &copy; copyright @ 2022 by <span>mr. web designer</span> | all rights reserved!

</footer>

{% endblock %}

   