E_learn/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views

from students.views import *
from lessons.views import *
urlpatterns = [
    path("admin/", admin.site.urls),
    path("", home, name='home'),
    path("about/", about, name='about'),
    path("register/", RegisterView.as_view(), name='register'),
    path("login/", CustomLoginView.as_view(), name='login'),
    path("logout/", auth_views.LogoutView.as_view(template_name='students/logout.html'), name='logout'),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('profile/', profile, name='profile'),
    path('courses/', courses, name='courses'),
    path('teachers/', teachers, name='teachers'),
    path('teacher_profile/<int:id>/', teacher_profile, name='teacher_profile'),
    path('profile/<int:pk>', owner_profile, name='owner_profile'),
    path('password-reset/', ResetPasswordView.as_view(), name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='students/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='students/password_reset_complete.html'),
         name='password_reset_complete'),
    path('profile/update/', update_profile, name='update_profile'),
    path('password-change/', ChangePasswordView.as_view(), name='password_change'),
    
    path(r'^ckeditor/', include('ckeditor_uploader.urls')), #ckeditor
    
    
    path('lesson/', include('lessons.urls', namespace='lesson')),
    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lessons/urls.py
from django.contrib import admin
from django.urls import path
from lessons import views
app_name = 'lessons'
urlpatterns = [
    path('search/', views.home, name='search'),
    path('course/liked_modules/', views.liked_modules, name='liked_modules'),
    path('course/view_comments/', views.view_comments, name='view_comments'),
    path('course/saved_playlists/', views.saved_playlists, name='saved_playlists'),
    
    path('<slug:category_slug>', views.home, name='index'),
    path('course/<slug:course_slug>/', views.course_detail, name='course_detail'),
    path('course/<slug:course_slug>/save', views.AddSave.as_view(), name='save_playlist'),
    

    path('course/<slug:course_slug>/<slug:module_slug>/', views.ModuleDetailView.as_view(), name='module_detail'),
    path('course/<slug:course_slug>/<slug:module_slug>/like', views.AddLike.as_view(), name='like'),
    path('course/<slug:course_slug>/<slug:module_slug>/dislike', views.AddDislike.as_view(), name='dislike'),
    path('course/<slug:course_slug>/<slug:module_slug>/edit/<int:comment_id>/', views.edit_comment, name='edit_comment'),
    path('course/<slug:course_slug>/<slug:module_slug>/update/<int:comment_id>/', views.update_comment, name='update_comment'),
    path('course/<slug:course_slug>/<slug:module_slug>/delete/<int:comment_id>/', views.delete_comment, name='delete_comment'),
    

]

lessons/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    comment = forms.CharField(max_length=1000,
        widget=forms.Textarea(attrs={
            "id": "comment_box",
            "placeholder": "enter your comment",
            "cols": 30,
            "rows": 10
            }))

    class Meta:
        model = Comment
        fields = ['comment']

lessons/views.py
from django.shortcuts import get_list_or_404, get_object_or_404, render
from django.core.paginator import Paginator
from django.urls import reverse
from lessons.forms import CommentForm
from lessons.utils import q_search
from lessons.models import Lesson, Category, Module, Comment
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
# Create your views here.

# def home (request):
    
    

#     lessons = Lesson.objects.all() 
    
    
#     categories = Category.objects.all()
#     context = {
#         "lessons" : lessons,
#         "categories":categories, 
#     }
    
#     return render(request, 'home.html', context)


def home (request, category_slug='all'):
    
    if request.user.is_authenticated:
        user_comments_count = Comment.objects.filter(author=request.user).count()
    else:
        user_comments_count = 0
    page = request.GET.get('page', 1)
    query = request.GET.get('q', None)
    
    if query:
        lessons = q_search(query)
    
    elif category_slug == 'all':
        lessons = Lesson.objects.all() 
        
    else:
        lessons = get_list_or_404(Lesson.objects.filter(category__slug=category_slug))
        
    if category_slug == 'all':
        current_category = 'all'
        
    else:
        current_category = (lessons[0].category)
        
    paginator = Paginator(lessons, 6)
    current_page = paginator.page(int(page))
    
    categories = Category.objects.all()

    context = {
        "lessons" : current_page,
        "categories":categories,
        "slug_url" : category_slug,
        "current_category": current_category,
        "count": user_comments_count
    }
    
    return render(request, 'home.html', context)

def about(request):
    return render(request, 'about.html')



def course_detail(request, course_slug):
    lesson = Lesson.objects.get(slug=course_slug)
    context = {
        "lesson": lesson
    }
    
    return render(request, 'lessons/playlist.html', context)

def course_posts(request):
    lessons = Lesson.objects.all()
    paginator = Paginator(lessons, 6)
    
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'home.html', {'page_obj': page_obj})

# def module_detail(request, course_slug, module_slug):
#     lesson = Lesson.objects.get(slug=course_slug)
#     module = lesson.modules.get(slug=module_slug)
    
#     context = {
#         'lesson': lesson,
#         "module": module
#     }
    
#     return render(request, 'lessons/module.html', context)

class AddLike(LoginRequiredMixin, View):
    
    def get(self, request, course_slug, module_slug, *args, **kwargs):
        lesson = get_object_or_404(Lesson, slug=course_slug)
        module = get_object_or_404(Module, lesson=lesson, slug=module_slug)
        context = {
            'lesson': lesson,
            'module': module
        }
        
        return render(request, 'lessons/module.html', context)
    
    
    
    def post(self, request, course_slug, module_slug, *args, **kwargs):
        lesson = get_object_or_404(Lesson, slug=course_slug)
        module = get_object_or_404(Module, lesson=lesson, slug=module_slug)

        is_dislike = False

        for dislike in module.dislikes.all():
            if dislike == request.user:
                is_dislike = True
                break

        if is_dislike:
            module.dislikes.remove(request.user)

        is_like = False

        for like in module.likes.all():
            if like == request.user:
                is_like = True
                break

        if not is_like:
            module.likes.add(request.user)

        if is_like:
            module.likes.remove(request.user)

        return redirect(request.META.get('HTTP_REFERER', '/'))
    
    
class AddDislike(LoginRequiredMixin, View):
    def post(self, request, course_slug, module_slug, *args, **kwargs):
        lesson = get_object_or_404(Lesson, slug=course_slug)
        module = get_object_or_404(Module, lesson=lesson, slug=module_slug)

        is_like = False

        for like in module.likes.all():
            if like == request.user:
                is_like = True
                break

        if is_like:
            module.likes.remove(request.user)

        is_dislike = False

        for dislike in module.dislikes.all():
            if dislike == request.user:
                is_dislike = True
                break

        if not is_dislike:
            module.dislikes.add(request.user)

        if is_dislike:
            module.dislikes.remove(request.user)

        return redirect(request.META.get('HTTP_REFERER', '/'))
    


class ModuleDetailView(View):
    def get(self, request, course_slug, module_slug):
        lesson = Lesson.objects.get(slug=course_slug)
        module = lesson.modules.get(slug=module_slug)
        form = CommentForm
        comments = Comment.objects.filter(module=module).order_by('-created_on')
        
        context = {
            'lesson': lesson,
            'module': module,
            'form': form,
            'comments': comments,
        }
        return render(request, 'lessons/module.html', context)
    
    @method_decorator(login_required)
    def post(self, request, course_slug, module_slug, *args, **kwargs):
        lesson = Lesson.objects.get(slug=course_slug)
        module = lesson.modules.get(slug=module_slug)        
        form = CommentForm(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.author = request.user
            new_comment.module = module
            new_comment.save()
            
            form = CommentForm()
    
        comments = Comment.objects.filter(module=module).order_by('-created_on')

        context = {
            'lesson':lesson,
            'module': module,
            'form': form,
            'comments': comments,
        }

        return render(request, 'lessons/module.html', context)
    
def edit_comment(request, course_slug, module_slug, comment_id):
    if request.method == 'POST':
        lesson = Lesson.objects.get(slug=course_slug)
        module = lesson.modules.get(slug=module_slug)
        comment = Comment.objects.get(pk=comment_id)
        comment_form = CommentForm(instance=comment)
        
        if comment_form.is_valid():
            comment_form.save()
            comment_form.author = request.user
            comment_form.module = module
            comment_form.save()
            
        comments = Comment.objects.filter(module=module).order_by('-created_on')
        
        context = {
            'lesson':lesson,
            'module': module,
            'form': comment_form,
            'comments': comments,
            'comment_id': comment_id,
            'edit': True
        }
        return render(request, 'lessons/module.html', context)
    
    
    
def update_comment(request, course_slug, module_slug, comment_id):
    
    
    if request.method == 'POST':
        lesson = Lesson.objects.get(slug=course_slug)
        module = lesson.modules.get(slug=module_slug)
        comment = Comment.objects.get(pk=comment_id)
        comment_form = CommentForm(request.POST, instance=comment)
        
        
        
        if comment_form.is_valid():
            updated_comment = comment_form.save(commit=False)  # Create a new instance but don't save it yet
            updated_comment.author = request.user
            updated_comment.module = module
            updated_comment.save()  # Save the updated comment
        
        else:
            comment = Comment.objects.get(pk=comment_id)
            comment_form = CommentForm(instance=comment)
        
        comments = Comment.objects.filter(module=module).order_by('-created_on')
    
        context = {
            'lesson':lesson,
            'module': module,
            'form': comment_form,
            'comments': comments,
            'comment_id': comment_id,
            'edit': True
        }
        return redirect(reverse('lesson:module_detail', args=[course_slug, module_slug]))
        
            
    
def delete_comment(request, course_slug, module_slug, comment_id):
    comment = Comment.objects.get(pk=comment_id)
    comment.delete()
    return redirect(reverse('lesson:module_detail', args=[course_slug, module_slug]))

class AddSave(LoginRequiredMixin, View):
    
    def get(self, request, course_slug):
        lesson = get_object_or_404(Lesson, slug=course_slug)
        context = {
            'lesson': lesson
        }
        
        return render(request, 'lessons/playlist.html', context)
    
    def post(self, request, course_slug):
        lesson = get_object_or_404(Lesson, slug=course_slug)
        if lesson.save.filter(id=request.user.id).exists():
            lesson.save.remove(request.user)
        else:
            lesson.save.add(request.user)
        
        context = {
            'lesson': lesson
        }
        # return redirect(request.META.get('HTTP_REFERER', '/'))
        return render(request, 'lessons/playlist.html', context )
    
@login_required
def liked_modules(request):
    if request.method == 'GET':
        user = request.user
        modules = Module.objects.filter(likes=user) 
        context = {
            'modules': modules  
        }
        
        return render(request, 'lessons/liked_modules.html', context)
        
def view_comments(request):
    
    user = request.user
    comments = Comment.objects.filter(author=user)
    
    context = {
        'comments': comments
    }
    
    return render(request, 'lessons/view_comments.html', context)

def saved_playlists(request):
    
    lessons = Lesson.objects.filter(save=request.user)
    

lessons/templates/lessons/liked_modules.html
{% extends "base.html" %}
{% load static %}
{% block title %} <title>Liked List</title> {% endblock %} 

{% block content %}



<section class="playlist-videos">

    <h1 class="heading">Liked Videos</h1>
 
    <div class="box-container">
 
       {% for module in modules %}
       <a class="box" href="{% url "lesson:module_detail" course_slug=module.lesson.slug module_slug=module.slug  %}">
          <i class="fas fa-play"></i>
          <img src="{{ module.image.url }}" alt="">
          <h3>{{ module.title }}</h3>
       </a>
       {% endfor %}
 
    </div>
 
</section>
 


 {% endblock %}

lessons/templates/lessons/module.html
{% extends "base.html" %}
{% load static %}
{% block title %} <title>Module</title> {% endblock %}
{% block content %}

<section class="watch-video">

   <div class="video-container">
      <div class="video">
         <video src="images/vid-1.mp4" controls poster="{{module.image.url}}" id="video"></video>
      </div>
      <h3 class="title">{{module.title}}</h3>
      <div class="info">
         <p class="date"><i class="fas fa-calendar"></i><span>{{lesson.created|date:"d-m-Y"}}</span></p>
         <p class="date"><i class="fas fa-heart"></i><span>{{module.likes.all.count}}</span></p>


         <!-- <p class="date"><i class="far fa-thumbs-down"></i><span>{{module.dislikes.all.count}}</span></p>

                                          For dislike count -->

      </div>
      <div class="tutor">
         <img src="{{lesson.owner.profile.image.url}}" alt="">
         <div>
            <h3>{{lesson.owner.first_name}} {{lesson.owner.last_name}}</h3>
            <span>{{lesson.owner}}</span>
         </div>
      </div>
      <form action="{% url 'lesson:like' course_slug=lesson.slug module_slug=module.slug %}" method="post" class="flex">
         {% csrf_token %}
         <a href="{% url "lesson:course_detail" lesson.slug %}" class="inline-btn">view playlist</a>
         <button><i class="far fa-heart"></i><span>like</span></button>
      </form>

      <!-- <form action="{% url 'lesson:dislike' course_slug=lesson.slug module_slug=module.slug %}" method="post" class="flex">
         {% csrf_token %}
         <button><i class="far fa-thumbs-down"></i><span>dislike</span></button>
      </form>
                                          For dislike button -->

      
      <p class="description">
         {{module.description}}
   </div>

</section>

<section class="comments">

   <h1 class="heading">{{comments.count}} comments</h1>
   {% if edit %}
      <form action="{% url 'lesson:update_comment' course_slug=lesson.slug module_slug=module.slug comment_id=comment_id %}" method="POST" class="add-comment">

   {% else %}
         <form action="{% url 'lesson:module_detail' course_slug=lesson.slug module_slug=module.slug %}" method="post" class="add-comment">
            {% endif %}
            {% csrf_token %}
            <h3>add comments</h3>
            <!-- <textarea></textarea> -->
            {{ form.comment }}
            <!-- <textarea name="comment_box" placeholder="enter your comment" required maxlength="1000" cols="30" rows="10"></textarea> -->
            <input type="submit" value="add comment" class="inline-btn" name="add_comment">
         </form>

   <h1 class="heading">user comments</h1>

   

   <div class="box-container">
      {% for comment in comments %}
      {% if comment.is_parent %}

      <div class="box">
         <div class="user">
            <img src="{{comment.author.profile.image.url}}" alt="">
            <div>
               <h3>{{comment.author.username}}</h3>
               <span>{{comment.created_on|date:"d-m-Y"}}</span>
            </div>
         </div>
         <div class="comment-box">{{comment.comment}}</div>
         
         {% if request.user == comment.author %}
         
            <div class="flex-btn">
               <form action="{% url 'lesson:edit_comment' course_slug=lesson.slug module_slug=module.slug comment_id=comment.id %}" method="POST">
                  {% csrf_token %}
                  <input type="submit" value="edit comment" name="edit_comment" class="inline-option-btn">
               </form>
               <form action="{% url 'lesson:delete_comment' course_slug=lesson.slug module_slug=module.slug comment_id=comment.id %}" method="">
                  {% csrf_token %}
                  <input type="submit" value="delete comment" name="delete_comment" class="inline-delete-btn">
               </form>
            </div>

         {% endif %}
         
        
      </div>
      {% endif %}
      {% endfor %}
      
   </div>

</section>

{% endblock %}

lessons/templates/lessons/module1.html
{% extends "base.html" %}
{% load static %}
{% block title %} <title>Module</title> {% endblock %}
{% block content %}

<section class="watch-video">

   <div class="video-container">
      <div class="video">
         <video src="images/vid-1.mp4" controls poster="{{module.image.url}}" id="video"></video>
      </div>
      <h3 class="title">{{module.title}}</h3>
      <div class="info">
         <p class="date"><i class="fas fa-calendar"></i><span>{{lesson.created|date:"d-m-Y"}}</span></p>
         <p class="date"><i class="fas fa-heart"></i><span>{{module.likes.all.count}}</span></p>


         <!-- <p class="date"><i class="far fa-thumbs-down"></i><span>{{module.dislikes.all.count}}</span></p>

                                          For dislike count -->

      </div>
      <div class="tutor">
         <img src="{{lesson.owner.profile.image.url}}" alt="">
         <div>
            <h3>{{lesson.owner.first_name}} {{lesson.owner.last_name}}</h3>
            <span>{{lesson.owner}}</span>
         </div>
      </div>
      <form action="{% url 'lesson:like' course_slug=lesson.slug module_slug=module.slug %}" method="post" class="flex">
         {% csrf_token %}
         <a href="{% url "lesson:course_detail" lesson.slug %}" class="inline-btn">view playlist</a>
         <button><i class="far fa-heart"></i><span>like</span></button>
      </form>

      <!-- <form action="{% url 'lesson:dislike' course_slug=lesson.slug module_slug=module.slug %}" method="post" class="flex">
         {% csrf_token %}
         <button><i class="far fa-thumbs-down"></i><span>dislike</span></button>
      </form>
                                          For dislike button -->

      
      <p class="description">
         {{module.description}}
   </div>

</section>

<section class="comments">

   <h1 class="heading">{{comments.count}} comments</h1>
   {% if edit %}
      <form action="{% url 'lesson:update_comment' course_slug=lesson.slug module_slug=module.slug comment_id=comment_id %}" method="POST" class="add-comment">

   {% else %}
      {% if user.is_authenticated %}
         <form action="{% url 'lesson:module_detail' course_slug=lesson.slug module_slug=module.slug %}" method="post" class="add-comment">

            {% csrf_token %}
            <h3>add comments</h3>
            <!-- <textarea></textarea> -->
            {{ form.comment }}
            <!-- <textarea name="comment_box" placeholder="enter your comment" required maxlength="1000" cols="30" rows="10"></textarea> -->
            <input type="submit" value="add comment" class="inline-btn" name="add_comment">
         </form>
      {% endif %}
   {% endif %}

   <h1 class="heading">user comments</h1>

   

   <div class="box-container">
      {% for comment in comments %}
      {% if comment.is_parent %}

      <div class="box">
         <div class="user">
            <img src="{{comment.author.profile.image.url}}" alt="">
            <div>
               <h3>{{comment.author.username}}</h3>
               <span>{{comment.created_on|date:"d-m-Y"}}</span>
            </div>
         </div>
         <div class="comment-box">{{comment.comment}}</div>
         
         {% if request.user == comment.author %}
         
            <div class="flex-btn">
               <form action="{% url 'lesson:edit_comment' course_slug=lesson.slug module_slug=module.slug comment_id=comment.id %}" method="POST">
                  {% csrf_token %}
                  <input type="submit" value="edit comment" name="edit_comment" class="inline-option-btn">
               </form>
               <form action="{% url 'lesson:delete_comment' course_slug=lesson.slug module_slug=module.slug comment_id=comment.id %}" method="">
                  {% csrf_token %}
                  <input type="submit" value="delete comment" name="delete_comment" class="inline-delete-btn">
               </form>
            </div>

         {% endif %}
         
        
      </div>
      {% endif %}
      {% endfor %}
      
   </div>

</section>

{% endblock %}

lessons/templates/lessons/playlist.html
{% extends "base.html" %}
{% load static %}

{% block title %} <title>Course</title> {% endblock %}

{% block content %}

<section class="playlist-details">

   <h1 class="heading">playlist details</h1>

   <div class="row">

      <div class="column">

   
         <div class="thumb">
            <img src="{{ lesson.image.url }}" alt="">
            <span>{{lesson.modules.count}} videos</span>
         </div>

         <form action="{% url 'lesson:save_playlist' course_slug=lesson.slug %}" method="post" class="save-playlist">
            {% csrf_token %}
            {% if lesson.save.exists %}
            <button type="submit"><i class="fa fa-bookmark"></i> <span>saved playlist</span></button>
            {% else %}
            <button type="submit"><i class="far fa-bookmark"></i> <span>save playlist</span></button>
            {% endif %}

         </form>

         
      </div>
      <div class="column">
         <div class="tutor">
               {% if request.user.pk != lesson.owner.pk %}
                  <a href="{% url 'owner_profile' pk=lesson.owner.pk %}"><img src="{{ lesson.owner.profile.image.url }}" alt=""></a>
               {% else %}
                  <a href="{% url 'profile' %}"><img src="{{ lesson.owner.profile.image.url }}" alt=""></a>
               {% endif %}

            <div>
               {% if request.user.pk != lesson.owner.pk %}
                  <a href="{% url 'owner_profile' pk=lesson.owner.pk %}"><h3>{{lesson.owner.first_name}} {{lesson.owner.last_name}}</h3></a>
               {% else %}
                  <a href="{% url 'profile' %}"><h3>{{lesson.owner.first_name}} {{lesson.owner.last_name}}</h3></a>
               {% endif %}
               <span>{{lesson.owner}}</span>
               <br>
               <span>{{lesson.created|date:"d-m-Y"}}</span>
            </div>
         </div>
   
         <div class="details">
            <h3>{{lesson.title}}</h3>
            <p>{{lesson.overview|safe}}</p> <!-- |linebreaksbr -->
            {% if request.user.pk != lesson.owner.pk %}
            <a href="{% url 'owner_profile' pk=lesson.owner.pk %}" class="inline-btn">view profile</a>
            {% else %}
            <a href="{% url 'profile' %}" class="inline-btn">view profile</a>
            {% endif %}

         </div>
      </div>
   </div>

</section>

<section class="playlist-videos">

   <h1 class="heading">playlist videos</h1>

   <div class="box-container">

      {% for module in lesson.modules.all %}
      <a class="box" href="{% url "lesson:module_detail" course_slug=lesson.slug module_slug=module.slug  %}">
         <i class="fas fa-play"></i>
         <img src="{{ module.image.url }}" alt="">
         <h3>{{ module.title }}</h3>
      </a>
      {% endfor %}

   </div>

</section>

{% endblock %}

lessons/templates/lessons/saved_playlists.html
{% extends "base.html" %}
{% load static %}
{% block title %} <title>Saved Playlists</title> {% endblock %} 

{% block content %}


    <section class="courses">
    <h1 class="heading">Saved Courses</h1>
    <div class="box-container">
      



        {% for lesson in lessons %}
     
     
           <div class="box">
              <div class="tutor">
                 <img src="{{ lesson.owner.profile.image.url }}" alt="{{lesson.owner}}">
                 <div class="info">
                    <h3>{{lesson.owner.first_name}} {{lesson.owner.last_name}}</h3>
                    <span>{{lesson.owner}}</span>
                    <br>
                    <span>{{lesson.created|date:"d-m-Y"}}</span>
                 </div>
              </div>
              <div class="thumb">
                 <a href="{% url "lesson:course_detail" lesson.slug %}"><img src="{{ lesson.image.url }}" alt=""></a>
                 <span>{{lesson.modules.count}} videos</span>
              </div>
              <h3 class="title">{{lesson.title}}</h3>
              <a href="{% url "lesson:course_detail" lesson.slug %}" class="inline-btn">view playlist</a>
           </div>
     
           
        {% endfor %}
              
     
    </div>

    </section>

{% endblock %}

lessons/templates/lessons/view_comments.html
{% extends "base.html" %}
{% load static %}
{% block title %} <title>Comments View</title> {% endblock %} 

{% block content %}

<section class="comments">

<h1 class="heading">user comments</h1>

   

   <div class="box-container">
      {% for comment in comments %}
      {% if comment.is_parent %}

      <div class="box">
         <div class="user">
            <img src="{{comment.author.profile.image.url}}" alt="">
            <div>
               <h3>{{comment.author.username}}</h3>
               <span>{{comment.created_on|date:"d-m-Y"}}</span>
            </div>
         </div>
         <div class="comment-box">{{comment.comment}}</div>
         
         {% if request.user == comment.author %}
         
            <div class="flex-btn">
               <form action="{% url "lesson:module_detail" course_slug=comment.module.lesson.slug module_slug=comment.module.slug  %}" method="POST">
                  {% csrf_token %}
                  <input type="submit" value="Link to Comment" name="edit_comment" class="inline-option-btn">
               </form>
            </div>

         {% endif %}
         
        
      </div>
      {% endif %}
      {% endfor %}
      
   </div>

</section>









{% endblock %}